# Project: DSAP_Final
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../src/Game.o ../src/GUI.o ../src/main.o ../src/Position.o ../src/Snake.o ../src/StraightForwardController.o
LINKOBJ  = ../src/Game.o ../src/GUI.o ../src/main.o ../src/Position.o ../src/Snake.o ../src/StraightForwardController.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"SFML-2.4.2/lib" -lsfml-audio -lsfml-window -lsfml-system -lsfml-graphics
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"SFML-2.4.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"SFML-2.4.2/include"
BIN      = DSAP_Final.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../src/Game.o: ../src/Game.cpp
	$(CPP) -c ../src/Game.cpp -o ../src/Game.o $(CXXFLAGS)

../src/GUI.o: ../src/GUI.cpp
	$(CPP) -c ../src/GUI.cpp -o ../src/GUI.o $(CXXFLAGS)

../src/main.o: ../src/main.cpp
	$(CPP) -c ../src/main.cpp -o ../src/main.o $(CXXFLAGS)

../src/Position.o: ../src/Position.cpp
	$(CPP) -c ../src/Position.cpp -o ../src/Position.o $(CXXFLAGS)

../src/Snake.o: ../src/Snake.cpp
	$(CPP) -c ../src/Snake.cpp -o ../src/Snake.o $(CXXFLAGS)

../src/StraightForwardController.o: ../src/StraightForwardController.cpp
	$(CPP) -c ../src/StraightForwardController.cpp -o ../src/StraightForwardController.o $(CXXFLAGS)
